# Generated by Django 5.1.1 on 2025-06-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='details',
        ),
    ]
